name: egypet_trip
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  go_router: ^14.1.4
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  gap: ^3.0.1
  get_it: ^7.7.0
  equatable: ^2.0.5
  flutter_tts: ^4.0.2
  image: ^3.0.1

  translator: ^1.0.0
  speech_to_text: ^6.6.2
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.1
  uuid: ^4.5.1
  flutter_svg: ^2.0.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.11.0+2
  flutter_tesseract_ocr: ^0.4.28



dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/tessdata/
    - assets/tessdata_config.json